title       = "ena"
baseURL     = "https://ena-cli.tamnd.com/"
description = "A command line for ena."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/ena-cli"
